// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_slug_index from "./routes/[slug]/index.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $blog_slug_index from "./routes/blog/[slug]/index.tsx";
import * as $blog_index from "./routes/blog/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $Blog_Avatar from "./islands/Blog/Avatar.tsx";
import * as $Blog_Body_Image from "./islands/Blog/Body-Image.tsx";
import * as $Blog_Body_Video from "./islands/Blog/Body-Video.tsx";
import * as $Blog_Code_Block from "./islands/Blog/Code-Block.tsx";
import * as $Blog_Cover_Image from "./islands/Blog/Cover-Image.tsx";
import * as $Blog_Intro from "./islands/Blog/Intro.tsx";
import * as $Blog_MoreBlogPosts from "./islands/Blog/MoreBlogPosts.tsx";
import * as $Blog_Post_Preview from "./islands/Blog/Post-Preview.tsx";
import * as $Blog_Post from "./islands/Blog/Post.tsx";
import * as $Blog_Posts_Hero_Post from "./islands/Blog/Posts/Hero-Post.tsx";
import * as $Blog_check_icon from "./islands/Blog/check-icon.tsx";
import * as $Blog_clipboard_icon from "./islands/Blog/clipboard-icon.tsx";
import * as $Blog_copy_to_clipboard from "./islands/Blog/copy-to-clipboard.tsx";
import * as $Blog_file_icon from "./islands/Blog/file-icon.tsx";
import * as $Blog_post_author from "./islands/Blog/post-author.tsx";
import * as $Blog_post_links from "./islands/Blog/post-links.tsx";
import * as $Blog_post_status from "./islands/Blog/post-status.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Ui_Badge_generate_effect from "./islands/Ui/Badge-generate-effect.tsx";
import * as $Ui_Text_generate_effect from "./islands/Ui/Text-generate-effect.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[slug]/index.tsx": $_slug_index,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/blog/[slug]/index.tsx": $blog_slug_index,
    "./routes/blog/index.tsx": $blog_index,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Blog/Avatar.tsx": $Blog_Avatar,
    "./islands/Blog/Body-Image.tsx": $Blog_Body_Image,
    "./islands/Blog/Body-Video.tsx": $Blog_Body_Video,
    "./islands/Blog/Code-Block.tsx": $Blog_Code_Block,
    "./islands/Blog/Cover-Image.tsx": $Blog_Cover_Image,
    "./islands/Blog/Intro.tsx": $Blog_Intro,
    "./islands/Blog/MoreBlogPosts.tsx": $Blog_MoreBlogPosts,
    "./islands/Blog/Post-Preview.tsx": $Blog_Post_Preview,
    "./islands/Blog/Post.tsx": $Blog_Post,
    "./islands/Blog/Posts/Hero-Post.tsx": $Blog_Posts_Hero_Post,
    "./islands/Blog/check-icon.tsx": $Blog_check_icon,
    "./islands/Blog/clipboard-icon.tsx": $Blog_clipboard_icon,
    "./islands/Blog/copy-to-clipboard.tsx": $Blog_copy_to_clipboard,
    "./islands/Blog/file-icon.tsx": $Blog_file_icon,
    "./islands/Blog/post-author.tsx": $Blog_post_author,
    "./islands/Blog/post-links.tsx": $Blog_post_links,
    "./islands/Blog/post-status.tsx": $Blog_post_status,
    "./islands/Counter.tsx": $Counter,
    "./islands/Ui/Badge-generate-effect.tsx": $Ui_Badge_generate_effect,
    "./islands/Ui/Text-generate-effect.tsx": $Ui_Text_generate_effect,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
